base_images:
  cli:
    name: "4.6"
    namespace: ocp
    tag: cli
binary_build_commands: make bin
build_root:
  project_image:
    dockerfile_path: openshift-ci/build-root/Dockerfile
images:
- context_dir: openshift-ci/build-root/source-image
  from: src
  inputs:
    cli:
      paths:
      - destination_dir: .
        source_path: /usr/bin/oc
  to: oc-bin-image
resources:
  '*':
    requests:
      cpu: 800m
      memory: 6Gi
tag_specification:
  name: "4.6"
  namespace: ocp
tests:
- as: e2e-4x-psi-mac
  steps:
    test:
    - as: e2e-4x-psi-mac-steps
      commands: sh scripts/openshiftci-e2e-4x-psi-tests_win_mac.sh mac
      credentials:
      - mount_path: /usr/local/ci-secrets/odo-rabbitmq
        name: odo-rabbitmq
        namespace: test-credentials
      env:
      - default: /usr/local/ci-secrets/odo-rabbitmq/amqpuri
        name: ODO_RABBITMQ_AMQP_URL
      from: oc-bin-image
      resources:
        requests:
          cpu: "2"
          memory: 6Gi
- as: unit-psi-mac
  steps:
    test:
    - as: unit-psi-mac-steps
      commands: sh scripts/openshiftci-unit-psi-tests_win_mac.sh mac
      credentials:
      - mount_path: /usr/local/ci-secrets/odo-rabbitmq
        name: odo-rabbitmq
        namespace: test-credentials
      env:
      - default: /usr/local/ci-secrets/odo-rabbitmq/amqpuri
        name: ODO_RABBITMQ_AMQP_URL
      from: oc-bin-image
      resources:
        requests:
          cpu: "2"
          memory: 6Gi
- as: unit-psi-windows
  steps:
    test:
    - as: unit-psi-windows-steps
      commands: sh scripts/openshiftci-unit-psi-tests_win_mac.sh win
      credentials:
      - mount_path: /usr/local/ci-secrets/odo-rabbitmq
        name: odo-rabbitmq
        namespace: test-credentials
      env:
      - default: /usr/local/ci-secrets/odo-rabbitmq/amqpuri
        name: ODO_RABBITMQ_AMQP_URL
      from: oc-bin-image
      resources:
        requests:
          cpu: "2"
          memory: 6Gi
- as: e2e-4x-psi-windows
  steps:
    test:
    - as: e2e-4x-psi-windows-steps
      commands: sh scripts/openshiftci-e2e-4x-psi-tests_win_mac.sh win
      credentials:
      - mount_path: /usr/local/ci-secrets/odo-rabbitmq
        name: odo-rabbitmq
        namespace: test-credentials
      env:
      - default: /usr/local/ci-secrets/odo-rabbitmq/amqpuri
        name: ODO_RABBITMQ_AMQP_URL
      from: oc-bin-image
      resources:
        requests:
          cpu: "2"
          memory: 6Gi
- as: integration-e2e-periodic
  cron: 0 */6 * * *
  steps:
    cluster_profile: aws
    test:
    - as: integration-e2e-periodic-steps
      commands: scripts/openshiftci-periodic-tests.sh
      from: oc-bin-image
      resources:
        requests:
          cpu: "2"
          memory: 6Gi
    workflow: ipi-aws
zz_generated_metadata:
  branch: master
  org: openshift
  repo: odo
  variant: v4.6
